on: push

name: Sample load secrets

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Debug
      run: |
        echo "key = ${{ secrets.SECRET_TEST }}"
